version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
      args:
        database_url: "postgresql://program:test@postgres:5432/persons"
    ports:
      - "8000:8000"
     depends_on:
      #CHANGE 2: it prevents issuing a request while the server is starting to depend on the healthy status of postgres-db 
      postgres:
        condition: service_healthy

volumes:
  db-data: