version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  
  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
      args:
        database_url: postgresql://pgsql_km2s_user:zL8bxyjG9knQpjPZSDBpdR8TDHosPyV3@dpg-ctit1252ng1s73bf2a60-a.oregon-postgres.render.com/pgsql_km2s
    ports:
      - "8000:8000"

volumes:
  db-data: